import * as React from 'react';
import { Container } from './styles';

function Content() {
  const experiences = [
    {
      role: 'Software Developer Consultant',
      company: 'ThoughtWorks',
      description:
        'Part of the Thoughtworks team as a consulting developer providing services to partner companies. Currently working at the partner company Globo with Javascript technology in the media player for the Player Web and TV platforms (eg Tizen, WebOS).',
      date: 'abr de 2021 - at moment',
    },
    {
      role: 'Front-End Engineer',
      company: 'Vibbra!',
      description:
        'Working as a Front-End Developer rebuilding internal systems using React, TypeScript and Material UI.',
      date: 'out de 2021 - at moment',
    },
    {
      role: 'Full-Stack Engineer',
      company: 'Mesa Mobile Thinking',
      description:
        'As a Full Stack Engineer I participated in projects in the areas of retail (Dashboard project), healthcare (Dashboard and public content area). Using tools like AdonisJs, PostgreSQL and SQL Server for backend development, Vue.Js for frontend development, Gitlab for versioning and Heroku for deploy in an agile environment with Scrum as the methodology.',
      date: 'mar de 2020 - fev de 2022',
    },
    {
      role: 'Front-End Engineer',
      company: 'Capyba',
      description: `Participated of the rebuild of a Brazil's relevant health project using Angular, TypeScript and Clean Architecture concepts.`,
      date: 'nov de 2021 - dez de 2021',
    },
    {
      role: 'Full-Stack Engineer',
      company: 'Kurier',
      description:
        'Analysis, development and maintenance of software systems for legal management where I developed the desktop and web version of Kurier Meridio using Delphi 10, AngularJs, SQL Server and SOAP. There are also database migrations from new customers to Kurier Meridio, creation of report scripts, analysis of scripts generated by support.',
      date: 'ago de 2019 - fev de 2020',
    },
    {
      role: 'Full-Stack Engineer',
      company: 'MV Sistemas',
      description:
        'Analysis, development and maintenance of software that helped hospitalar management. I worked as developer of the international version of SoulMV using proprietary framework based on Spring Boot, GitLab for versioning, Oracle for database and Java programming language.',
      date: 'ago de 2018 - ago de 2019',
    },
  ];

  const educations = [
    {
      name: 'Bacharelado em Engenharia de Computação',
      organization: 'Faculdade Maurício de Nassau',
      date: 'jan de 2015 - dez de 2019',
    },
    {
      name: 'Aluna Bootcamp GoStack 8.0, FullStack Developer',
      organization: 'Rocketseat',
      date: 'julho de 2019 - dez de 2019',
    },
  ];

  const certifications = [
    {
      name: 'Automação Front End com NPM',
      organization: 'Origamid',
      date: 'Emitido em mar de 2020',
    },
    {
      name: 'CSS Avançado',
      organization: 'Origamid',
      date: 'Emitido em mar de 2020',
    },
    {
      name: 'Bootstrap 4',
      organization: 'Origamid',
      date: 'Emitido em out de 2018',
    },
    {
      name: 'UX Design - Heurísticas',
      organization: 'Origamid',
      date: 'Emitido em jul de 2018',
    },
    {
      name: 'Web Design Completo',
      organization: 'Origamid',
      date: 'Emitido em jul de 2018',
    },
  ];

  return (
    <Container>
      <div>
        <div className="experience">
          <span className="title">Experience</span>

          {experiences.map((experience) => (
            <div key={experience.company}>
              <span>
                <strong>{experience.role},</strong> {experience.company}
              </span>

              <h6>{experience.date}</h6>

              <p>{experience.description}</p>
            </div>
          ))}
        </div>
      </div>

      <div>
        <div className="education">
          <span className="title">Academic Education</span>

          {educations.map((education) => (
            <div key={education.organization}>
              <span>
                <strong>{education.name},</strong>
                <br />
                {education.organization}
              </span>

              <h6> {education.date}</h6>
            </div>
          ))}
        </div>
        <div className="education">
          <span className="title">Certificates</span>

          {certifications.map((certification) => (
            <div key={certification.name}>
              <span>
                <strong>{certification.name},</strong>
                <br />
                {certification.organization}
              </span>

              <h6>{certification.date}</h6>
            </div>
          ))}
        </div>
        <div className="education">
          <span className="title">Skills</span>
          <div>
            <span>
              React · Javascript · Node.js · Typescript · HTML · CSS · Bootstrap · Material UI · Postgres · SQL Server ·
              Adonis.js
            </span>
          </div>
        </div>
      </div>
    </Container>
  );
}

export default Content;
